### ISSUE TITLE
Glacier redundancy

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop-clients#16]
### Summary
<table>
  <tr>
    <td><b>As an</b></td>
    <td>archivist</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       ensure my data is sent to a long-term archive is a separate region (us-west-2)
    </td>
  </tr>
  <tr>
    <td><b>So that I can</b></td>
    <td>that I have a backup copy in a different geography that supports COOP</td>
  </tr>
</table>

### Tasks
- [x] Create vault
- [x] Upgrade onestop-python-client to support sending data to glacier in a separate region
- [x] Modify code to use s3 api over existing use of glacier
- [x] Create utility class to restore from glacier for testing purposes
