### ISSUE TITLE
Complete s3 metadata generation and capture by CSB/Data Lake

### ISSUE THREAD

**Issue by dneufeldcu** [cedardevs/onestop-clients#6]
### Summary
<table>
  <tr>
    <td><b>As a</b></td>
    <td>NOAA data discovery system</td>
  </tr>
  <tr>
    <td><b>I want to be able to</b></td>
    <td>
       generically capture file level metadata
    </td>
  </tr>
  <tr>
    <td><b>So that I can be</b></td>
    <td>ready for a capturing all data streams at NOAA</td>
  </tr>
</table>

### Tasks
- [x] Add CSB metadata to loader script in onestop-test-data
- [x] Finish lambda to post to registry-api
- [x] Capture of URL based on public access point of s3 bucket
