### ISSUE TITLE
Python s3 event to SQS consumer to IM Registry

### ISSUE THREAD

**Issue by mcquinne** [cedardevs/onestop-clients#7]
Currently the Python SQS consumer in the cloud installation POSTs JSON into the Registry API. That's all well and good, but if it were to produce messages directly to Kafka that would decrease network bandwidth as well as the number of hops required, plus we'd get the benefits of the librdkafka producer library, like batching, retries, failover, etc.

### Tasks:
- [x] Add producer support to the python onestop-client for collections
- [x] Use python onestop-client to consume from sqs consumer
- [x] Add s3 message adapter to translate s3 message to IM format
- [x] Add unit tests
- [x] Add a e2e integration script
- [x] Load data into glacier from s3

### Considerations
- Arvo schemas for serialization
    - The client will need to get the schema to use in serializing... i.e. the opposite of what the consumer does
    - **Should** be able to retrieve the schema based on the target topic, I think
- Support for batches
    - It would be great if the produce function could handle a collection of messages in order to leverage the kafka producer's ability to batch messages
- Support for consumer configs
    - Like the consumer, users of the producer function should be able to pass full producer configs, e.g. compression codec
